# This workflow is used to test the action

on:
  push:
  pull_request:

jobs:
  build_pure:
    name: Test action (pure wheel)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: ./
        with:
          pure_python_wheel: true
          test_extras: test
          test_command: pytest --pyargs test_package
  build_non_pure:
    name: Test action (not pure wheel)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - id: build_not_pure
        uses: ./
        with:
          pure_python_wheel: "false"
          test_extras: test
          test_command: pytest --pyargs test_package
